[phases.setup]
nixPkgs = ['python312']

[phases.install]
cmds = ['cd BACKEND && pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'cd BACKEND && python -m uvicorn main:app --host 0.0.0.0 --port $PORT'