# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "mkdir -p logs ml_models data temp",
    "python BACKEND/create_dirs.py"
]

[start]
cmd = "python BACKEND/main.py"